[labels]
app_name = Projects

notification_topic_update_created = New objects
notification_topic_update_modified = Object changes
notification_topic_assignment = Assignments
notification_topic_mention = Mentions
