/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ProjectIdDiffRouteImport } from './routes/$projectId.diff'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedProjectIdIndexRouteImport } from './routes/_authenticated/$projectId/index'
import { Route as AuthenticatedProjectIdObjectIdRouteImport } from './routes/_authenticated/$projectId/$objectId'
import { Route as AuthenticatedProjectIdDesignRouteImport } from './routes/_authenticated/$projectId/design'
import { Route as AuthenticatedProjectIdSettingsRouteImport } from './routes/_authenticated/$projectId_.settings'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdDiffRoute = ProjectIdDiffRouteImport.update({
  id: '/$projectId/diff',
  path: '/$projectId/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectIdIndexRoute =
  AuthenticatedProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectIdObjectIdRoute =
  AuthenticatedProjectIdObjectIdRouteImport.update({
    id: '/$projectId/$objectId',
    path: '/$projectId/$objectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectIdDesignRoute =
  AuthenticatedProjectIdDesignRouteImport.update({
    id: '/$projectId/design',
    path: '/$projectId/design',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectIdSettingsRoute =
  AuthenticatedProjectIdSettingsRouteImport.update({
    id: '/$projectId_/settings',
    path: '/$projectId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$projectId/diff': typeof ProjectIdDiffRoute
  '/find': typeof AuthenticatedFindRoute
  '/$projectId/$objectId': typeof AuthenticatedProjectIdObjectIdRoute
  '/$projectId/design': typeof AuthenticatedProjectIdDesignRoute
  '/$projectId/settings': typeof AuthenticatedProjectIdSettingsRoute
  '/$projectId/': typeof AuthenticatedProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/$projectId/diff': typeof ProjectIdDiffRoute
  '/find': typeof AuthenticatedFindRoute
  '/': typeof AuthenticatedIndexRoute
  '/$projectId/$objectId': typeof AuthenticatedProjectIdObjectIdRoute
  '/$projectId/design': typeof AuthenticatedProjectIdDesignRoute
  '/$projectId/settings': typeof AuthenticatedProjectIdSettingsRoute
  '/$projectId': typeof AuthenticatedProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$projectId/diff': typeof ProjectIdDiffRoute
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$projectId/$objectId': typeof AuthenticatedProjectIdObjectIdRoute
  '/_authenticated/$projectId/design': typeof AuthenticatedProjectIdDesignRoute
  '/_authenticated/$projectId_/settings': typeof AuthenticatedProjectIdSettingsRoute
  '/_authenticated/$projectId/': typeof AuthenticatedProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId/diff'
    | '/find'
    | '/$projectId/$objectId'
    | '/$projectId/design'
    | '/$projectId/settings'
    | '/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$projectId/diff'
    | '/find'
    | '/'
    | '/$projectId/$objectId'
    | '/$projectId/design'
    | '/$projectId/settings'
    | '/$projectId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/$projectId/diff'
    | '/_authenticated/find'
    | '/_authenticated/'
    | '/_authenticated/$projectId/$objectId'
    | '/_authenticated/$projectId/design'
    | '/_authenticated/$projectId_/settings'
    | '/_authenticated/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ProjectIdDiffRoute: typeof ProjectIdDiffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/diff': {
      id: '/$projectId/diff'
      path: '/$projectId/diff'
      fullPath: '/$projectId/diff'
      preLoaderRoute: typeof ProjectIdDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$projectId/': {
      id: '/_authenticated/$projectId/'
      path: '/$projectId'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$projectId/$objectId': {
      id: '/_authenticated/$projectId/$objectId'
      path: '/$projectId/$objectId'
      fullPath: '/$projectId/$objectId'
      preLoaderRoute: typeof AuthenticatedProjectIdObjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$projectId/design': {
      id: '/_authenticated/$projectId/design'
      path: '/$projectId/design'
      fullPath: '/$projectId/design'
      preLoaderRoute: typeof AuthenticatedProjectIdDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$projectId_/settings': {
      id: '/_authenticated/$projectId_/settings'
      path: '/$projectId/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectIdObjectIdRoute: typeof AuthenticatedProjectIdObjectIdRoute
  AuthenticatedProjectIdDesignRoute: typeof AuthenticatedProjectIdDesignRoute
  AuthenticatedProjectIdSettingsRoute: typeof AuthenticatedProjectIdSettingsRoute
  AuthenticatedProjectIdIndexRoute: typeof AuthenticatedProjectIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectIdObjectIdRoute: AuthenticatedProjectIdObjectIdRoute,
  AuthenticatedProjectIdDesignRoute: AuthenticatedProjectIdDesignRoute,
  AuthenticatedProjectIdSettingsRoute: AuthenticatedProjectIdSettingsRoute,
  AuthenticatedProjectIdIndexRoute: AuthenticatedProjectIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ProjectIdDiffRoute: ProjectIdDiffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
